### ISSUE TITLE
What is bin file type????

### ISSUE THREAD

**Issue by sarpulas** [novitai/skycompress#7]
It's all binary fam https://novit-ai.slack.com/archives/CC4G11QDN/p1696490473236659?thread_ts=1696489187.491539&cid=CC4G11QDN

**Comment by furkannnnnnnnn** [comment]
I say we remove `bin` and `gry`.

@sarpulas we have not needed those ever.

https://github.com/novitai/ultra-secret-project/blob/1f18b6e277e34acdcd8c149c57d70a7003497c12/legacy/image_compressor.py#L14

**Comment by Gozgur** [comment]
checked but couldn't find any useful information. and we do not use both of them bin and grey in the code. it is wrong or something

**Comment by furkannnnnnnnn** [comment]
Have we tried the script on grayscale images, by inspecting output images?

**Comment by furkannnnnnnnn** [comment]
We have now, but the code is a bit coupled. @Gozgur can you open an issue to get rid of `bin` and remove the repetition among `gry` and `rgb`?

**Comment by Gozgur** [comment]
https://en.wikipedia.org/wiki/Binary_image

What is a binary color?
noun. : a color made by mixing two primary colors : secondary color.

**Comment by sarpulas** [comment]
OH okay so grayscale is black->white with every shade in gray in between
Binary is ONLY black or white

<img width="303" alt="Screenshot 2023-10-16 at 15 08 27" src="https://github.com/novitai/skycompress/assets/1934589/bdfc4e39-a947-444e-a390-64edd56d8e98">


![image](https://github.com/novitai/skycompress/assets/1934589/4744c95e-ce1d-4327-a0be-2cf0c92584ff)

power of googling your question
